print("Hello, world")
print("My name is Amal.")
print("I'm going to talk about my daily routine.")
print("In the morning, I wake up and brush my teeth.")
print("Eat breakfast.")
print("Watch tv.")
print("Eat lunch")
print("Watch tv with my family.")
print("Go outside and play")
print("Come back inside and drink tea.")
print("Take a bath.")   
print("Watch my phone.")
print("Watch a movie with my family.")
print("Brush teeth.")
print("Go to bed.")